/**
 * Smoke test: does a PRD GENERATED by PRDGenerator pass the strict
 * 14-dimension open-stage gate (p0Count===0 && p1Count===0 && score>=90)?
 * If it does NOT, the loop can never leave the "open" stage in production
 * (real flow break). This proves the generator↔gate contract.
 */
import { PRDGenerator, PRDChecker } from '../packages/core/dist/index.js';

const gen = new PRDGenerator();
const prd = gen.generate({
  title: 'Local Todo CLI',
  description:
    'A minimal cross-platform CLI to manage todos. Pain: existing tools are cloud-locked. ' +
    'AzaLoop should drive PRD → spec → code → ship with real gates.',
});

const checker = new PRDChecker();
const res = checker.check(prd);

console.log('PRD fields present:', Object.keys(prd).join(', '));
console.log('--- GATE RESULT ---');
console.log('passed   :', res.passed);
console.log('score    :', res.score, '(need >=90)');
console.log('p0_count :', res.p0_count, '(need 0)');
console.log('p1_count :', res.p1_count, '(need 0)');
console.log('p2_count :', res.p2_count);
console.log('p3_count :', res.p3_count);
console.log('--- FAILED DIMENSIONS ---');
for (const d of res.details.filter((x) => !x.passed)) {
  console.log(`  [${d.severity}] ${d.dimension}: ${d.description}${d.suggestion ? ' — ' + d.suggestion : ''}`);
}

const gateOk = res.p0_count === 0 && res.p1_count === 0 && res.score >= 90;
console.log('\nGATE_OK (loop can leave open):', gateOk);
process.exit(gateOk ? 0 : 2);
