
const fs = require('fs');
const path = 'D:/work_code/azaloop/azaloop/docs/competitive-analysis/AzaLoop-18项目深度对比与优化方案-2026-07-14.md';
const lines = [];
lines.push('# AzaLoop 18 项目深度对比与优化重构方案');
lines.push('');
lines.push('> 日期: 2026-07-14');
lines.push('> 基于: 18 个参考项目源码实证分析 + AzaLoop v0.1.0 源码审计');
lines.push('> 输出目录: docs/competitive-analysis/');
lines.push('');
lines.push('---');
lines.push('');
lines.push('## 1. 项目主体流程贯通性审计');
lines.push('');
lines.push('### 1.1 核心链路');
lines.push('');
lines.push('```');
lines.push('aza_session(calibrate) -> aza_prd(review->approve) -> aza_loop(full) <-> aza_spec/aza_quality + report_tool -> aza_finish(ship)');
lines.push('```');
lines.push('');
lines.push('### 1.2 逐层贯通性检查');
lines.push('');
lines.push('| 层级 | 模块 | 贯通状态 | 详细说明 |');
lines.push('|------|------|----------|----------|');
lines.push('| L0 平台 | client-detection.ts | 贯通 | 25+ 客户端检测，T1/T2/T3 分级 |');
lines.push('| L0 平台 | template-generator.ts | 贯通 | 各客户端规则模板生成 |');
lines.push('| L0 平台 | compensation-strategy.ts | 贯通 | T2/T3 客户端降级补偿策略 |');
lines.push('| L0 平台 | plugin-loader.ts | 贯通 | v14 P8.6 ruflo 模式插件加载 |');
lines.push('| L0 平台 | workers/ (12 workers) | 贯通 | ultralearn/optimize/consolidate/predict 等 |');
lines.push('| L1 Spec | prd-generator.ts | 贯通 | 14 维度 PRD 生成 + 自优化 |');
lines.push('| L1 Spec | prd-checker.ts | 贯通 | 14 维度检查 |');
lines.push('| L1 Spec | prd-review-gate.ts | 贯通 | C5 门禁 |');
lines.push('| L1 Spec | prd-multi-role-review.ts | 贯通 | CEO/QA/Eng 多角色审查 |');
lines.push('| L1 Spec | github-competitive-research.ts | 贯通 | GitHub API 竞品搜索注入 PRD |');
lines.push('| L1 Spec | change-management.ts | 贯通 | OpenSpec 变更管理 |');
lines.push('| L1 Spec | change-folder.ts | 贯通 | ralphy-openspec 模式变更文件夹 |');
lines.push('| L1 Spec | execution-contract.ts | 贯通 | T17 spec-superflow 执行合约 |');
lines.push('| L1 Spec | adr.ts | 贯通 | Trellis MADR 架构决策记录 |');
lines.push('| L1 Spec | constitution.ts | 贯通 | 项目章程 |');
lines.push('| L1 Spec | brainstorming-red-flags.ts | 贯通 | superpowers 模式头脑风暴红旗 |');
lines.push('| L2 记忆 | 13 个模块 | 贯通 | 三层记忆 + 向量存储 + 压缩 + 上下文编排 |');
lines.push('| L3 角色 | dynamic-binder.ts + subagent-roles.ts | 贯通 | 动态角色绑定 + 子代理分发 |');
lines.push('| L4 纪律 | 4 个模块 | 贯通 | 3-strike + TDD 铁律 + 失败分类 + 验证短语 |');
lines.push('| L5 技能 | registry.ts + composer.ts | 贯通 | 技能注册表 + 组合器 |');
lines.push('| L6 安全 | 9 个模块 | 贯通 | 7 扫描器 + ShellWard + 合规检查 + UI QA |');
lines.push('| L7 循环 | 25+ 模块 | 贯通 | 状态机 + 三级循环 + 断路器 + DAG + 哨兵 |');
lines.push('| L8 编排 | 7 个模块 | 贯通 | 模型路由 + 蜂群 + 工作树 + YAML 编排 + 联邦 |');
lines.push('| L9 知识 | 3 个模块 | 贯通 | 注入引擎 + 断环分析 + 因果边 |');
lines.push('| 质量 | 7 个门禁 | 贯通 | lint/test/regression/security/acceptance/loop-audit/adr |');
lines.push('| 连续性 | 5 个模块 | 贯通 | 恢复 + 追赶 + 上下文注入 + 事件模拟 |');
lines.push('| 状态 | 4 个模块 | 贯通 | 状态管理器 + 校验和 + 心跳 + 账本 |');
lines.push('| Hook | 6+ 模块 | 贯通 | 事件总线 + 生命周期 + MCP 桥接 |');
lines.push('| CLI | 8 个命令 | 贯通 | init/setup/loop/continue/pack/upgrade/budget/audit |');
lines.push('');
lines.push('### 1.3 贯通性结论');
lines.push('');
lines.push('**主体流程已完全贯通。** 从 L0 到 L9 的 10 层架构、质量流水线、连续性系统、Hook 事件系统、CLI 命令全部接线。AzaLoop 在架构完整性上已经超越了所有 18 个参考项目。');
fs.writeFileSync(path, lines.join('
'), 'utf8');
console.log('Written successfully');
